apiVersion: v1
kind: Pod
metadata:
   name: registry-pull-pod
spec:
   # serviceAccountName: aws-registry-sa
   volumes:
   - name: kubeconfig-dir
     hostPath:
       path: /etc/kubernetes
       type: Directory
   containers:
   - name: registry-pull-container
     image: chhabra/aws-kubectl-ecr-pull:1.1
     volumeMounts:
     - name: kubeconfig-dir
       mountPath: /mnt
     securityContext:
       allowPrivilegeEscalation: true
     env:
     - name: KUBECONFIG
       value: "/mnt/eks-kubelet-kubeconfig.yaml"
     - name: AWS_ACCOUNT
       value: "258057316678"
     - name: AWS_REGION
       value: us-east-1